[package]
name = "proteus"
version = "0.1.0"
edition = "2024"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = true

[dependencies]
brotli = "9"
bytes = "1"
flate2 = "1"
headers = "0.4"
http-body = "1"
http-body-util = "0.1"
httpdate = "1"
hyper = { version = "1", features = ["http1", "server"] }
hyper-util = { version = "0.1", features = ["tokio", "server", "http1"] }
ipnetwork = { version = "0.21.1", features = ["serde"] }
libc = "0.2"
libloading = "0.9"
mimalloc = "0.1.52"
mime_guess = "2"
nix = { version = "0.31.3", features = ["event", "fs", "process", "socket", "user", "uio", "signal"] }
parking_lot = "0.12"
postcard = { version = "1", features = ["alloc"] }
regex = { version = "1", default-features = false, features = ["std", "perf"] }
serde = { version = "1", features = ["derive"] }
serde_bytes = "0.11"
serde_json = "1"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "process", "io-util", "time", "fs", "signal"] }
tokio-seqpacket = "0.9"
tokio-stream = "0.1"
tokio-util = { version = "0.7", features = ["io"] }
tracing = "0.1"
tracing-appender = "0.2"
tracing-subscriber = { version = "0.3", default-features = false, features = ["json", "fmt"] }
zstd = "0.14"

[dev-dependencies]
reqwest = { version = "0.13.4", default-features = false, features = ["gzip", "json", "multipart"] }
